### ISSUE TITLE
Login failed message

### ISSUE THREAD

**Issue by AlvoErrado2** [jaw20/Crunchyroll-XML-Decoder#18]
I have a trial account until March 10. I tried to log in as a premium user and receive the 'Login failed' message. Any fixes for this or is the problem with the trial account?

Thank You

**Comment by shinji257** [comment]
In Membership does it show as Premium or Premium+?  This makes a difference so I would like to know.

**Comment by AlvoErrado2** [comment]
Problem solved for now, I tested a solution proposed in another topic: https://github.com/jaw20/Crunchyroll-XML-Decoder/pulls

**Comment by shinji257** [comment]
So in other words my proposed (potential) Premium+ fix?

**Comment by shinji257** [comment]
Just in case anyone was wondering the proposed fix he used was https://github.com/jaw20/Crunchyroll-XML-Decoder/pull/17.  I fixed that patch though since it potentially detects Premium detection from looking in the wrong spot.  At least it would of for trials.  Resubmitted as https://github.com/jaw20/Crunchyroll-XML-Decoder/pull/18.
